In [298]:
import matplotlib.pyplot as plt
import pandas as pd
import requests as r
import re

In [300]:
def load_data(filepath,sheet):
    #df = pd.read_excel(open(filepath,'rb'),sheet_name=sheet)
    df = pd.read_excel(filepath,sheet_name=sheet)
    
    return df

df = load_data('published-data/development-of-the-mouse-and-human-cochlea-at-single-cell-resolution/media-2.xlsx',
               'epi_data_matrix')

# Rename the first column to something useful
df.rename(columns={'Unnamed: 0':'Gene'},inplace=True)

# Display the first 10 rows
df.head(10) # or tail(10) will show the bottom 3

,Unnamed: 0,10.0_Mean,10.0_SD,10.0_Avg_diff,10.0_Pval,10.1.0_Mean,10.1.0_SD,10.1.0_Avg_diff,10.1.0_Pval,10.1.1_Mean,...,22.3_Avg_diff,22.3_Pval,24.0_Mean,24.0_SD,24.0_Avg_diff,24.0_Pval,24.1_Mean,24.1_SD,24.1_Avg_diff,24.1_Pval
0,Apoe,-0.454713,0.449679,-0.891624,2.595464e-35,0.271620,0.903053,0.573273,5.168455e-10,-0.339086,...,-0.39749,7.824495e-12,-0.312228,0.468616,-0.731901,0.000001,-0.137722,0.570408,-0.419621,0.000013
1,Bmp4,-0.358305,0.295937,NaN,NaN,3.982299,1.615688,2.097418,3.029520e-97,1.373414,...,NaN,NaN,-0.159035,0.693488,NaN,NaN,-0.168210,0.697095,NaN,NaN
2,Npnt,-0.100410,0.644706,NaN,NaN,1.524796,2.447777,0.781121,4.317224e-17,0.138519,...,NaN,NaN,-0.061202,0.420073,NaN,NaN,0.006049,0.649601,NaN,NaN
3,Lmo3,-0.103131,0.334746,NaN,NaN,5.723087,4.423924,1.310493,1.149371e-57,1.298182,...,NaN,NaN,0.091927,1.295068,NaN,NaN,-0.094702,0.027537,NaN,NaN
4,Hs3st1,-0.185846,0.414893,-0.826899,5.349538e-46,3.594417,1.862352,1.401558,8.687586e-65,2.588052,...,NaN,NaN,-0.081855,0.626980,NaN,NaN,-0.070822,0.537126,NaN,NaN
5,Gata2,-0.140274,0.627782,NaN,NaN,4.035117,2.805363,1.373971,9.390760e-56,1.957764,...,NaN,NaN,-0.075350,0.783816,NaN,NaN,0.125897,1.223989,NaN,NaN
6,Mest,-1.007405,0.603536,-0.367468,4.788085e-20,-0.490894,0.826415,0.411888,1.222823e-05,-0.879991,...,NaN,NaN,-0.778942,0.698958,NaN,NaN,-0.828148,0.747791,NaN,NaN
7,Krt18,0.474788,1.298400,-0.613109,1.670026e-27,1.139663,1.546185,NaN,NaN,2.085509,...,NaN,NaN,0.670491,1.146938,-0.530948,0.000001,0.623360,1.282659,-0.485152,0.000573
8,Igfbp4,-0.958780,0.333678,NaN,NaN,-0.293656,0.798151,0.772070,4.570655e-18,-0.629813,...,NaN,NaN,-0.810867,0.494231,NaN,NaN,-0.792913,0.443284,NaN,NaN
9,Rnd2,0.079147,1.122124,-0.408460,3.507536e-21,2.563297,2.544600,0.776573,4.637550e-22,0.534591,...,NaN,NaN,-0.020253,0.787430,NaN,NaN,0.101593,1.151177,NaN,NaN

In [301]:
df.columns

Index(['Unnamed: 0', '10.0_Mean', '10.0_SD', '10.0_Avg_diff', '10.0_Pval',
       '10.1.0_Mean', '10.1.0_SD', '10.1.0_Avg_diff', '10.1.0_Pval',
       '10.1.1_Mean', '10.1.1_SD', '10.1.1_Avg_diff', '10.1.1_Pval',
       '10.1.2_Mean', '10.1.2_SD', '10.1.2_Avg_diff', '10.1.2_Pval',
       '10.1.3_Mean', '10.1.3_SD', '10.1.3_Avg_diff', '10.1.3_Pval',
       '10.2.0_Mean', '10.2.0_SD', '10.2.0_Avg_diff', '10.2.0_Pval',
       '10.2.1_Mean', '10.2.1_SD', '10.2.1_Avg_diff', '10.2.1_Pval',
       '10.3.0_Mean', '10.3.0_SD', '10.3.0_Avg_diff', '10.3.0_Pval',
       '10.3.1_Mean', '10.3.1_SD', '10.3.1_Avg_diff', '10.3.1_Pval',
       '10.3.2_Mean', '10.3.2_SD', '10.3.2_Avg_diff', '10.3.2_Pval',
       '10.4_Mean', '10.4_SD', '10.4_Avg_diff', '10.4_Pval', '10.5_Mean',
       '10.5_SD', '10.5_Avg_diff', '10.5_Pval', '22.0_Mean', '22.0_SD',
       '22.0_Avg_diff', '22.0_Pval', '22.1_Mean', '22.1_SD', '22.1_Avg_diff',
       '22.1_Pval', '22.2.0_Mean', '22.2.0_SD', '22.2.0_Avg_diff',
       '22.2.0_Pval', '22.2.1_Mean', '22.2.1_SD', '22.2.1_Avg_diff',
       '22.2.1_Pval', '22.3_Mean', '22.3_SD', '22.3_Avg_diff', '22.3_Pval',
       '24.0_Mean', '24.0_SD', '24.0_Avg_diff', '24.0_Pval', '24.1_Mean',
       '24.1_SD', '24.1_Avg_diff', '24.1_Pval'],
      dtype='object')

In [271]:
# Isolate groups making up the cochlea floor
# Use list comprehension to join suffix to groups
suffix = '_Avg_diff'
all_groups = ['10.1.1','10.1.2','10.1.3','10.2.0','10.2.1','10.3.0','10.3.1',\
             '10.3.2','10.4','10.5','22.0','22.1','22.2.0','22.2.1','22.3',\
             '24.0','24.1']
early_groups = ['24.0','24.1','10.0','10.1.0','10.1.1','10.4','10.2.1','10.3.0']
cycling_groups = ['10.0','24.0','24.1']

all_diffs = [group + suffix for group in all_groups]
early_diffs = [group + suffix for group in early_groups]
cycling_diffs = [group + suffix for group in cycling_groups]

# Rename the first column to something useful
df.rename(columns={'Unnamed: 0':'Gene'},inplace=True)
# From Figure 3, select the clusters in the floor corresponding to earliest timepoints

# Get just the columns we're interested (average differential expression)
cols = all_diffs
cols.insert(0,'Gene')
df_alldiffs = df[cols]

cols = early_diffs
cols.insert(0,'Gene')
df_earlydiffs = df[cols]

cols = cycling_diffs
cols.insert(0,'Gene')
df_cyclingdiffs = df[cols]

In [304]:
cols = ['Gene'] + all_diffs
cols

['Gene',
 'Gene',
 '10.1.1_Avg_diff',
 '10.1.2_Avg_diff',
 '10.1.3_Avg_diff',
 '10.2.0_Avg_diff',
 '10.2.1_Avg_diff',
 '10.3.0_Avg_diff',
 '10.3.1_Avg_diff',
 '10.3.2_Avg_diff',
 '10.4_Avg_diff',
 '10.5_Avg_diff',
 '22.0_Avg_diff',
 '22.1_Avg_diff',
 '22.2.0_Avg_diff',
 '22.2.1_Avg_diff',
 '22.3_Avg_diff',
 '24.0_Avg_diff',
 '24.1_Avg_diff']

In [218]:
# Access rows by their indices (0-based)
df.iloc[[10,20,30]]

,Gene,10.0_Mean,10.0_SD,10.0_Avg_diff,10.0_Pval,10.1.0_Mean,10.1.0_SD,10.1.0_Avg_diff,10.1.0_Pval,10.1.1_Mean,...,22.3_Avg_diff,22.3_Pval,24.0_Mean,24.0_SD,24.0_Avg_diff,24.0_Pval,24.1_Mean,24.1_SD,24.1_Avg_diff,24.1_Pval
10,Rtn1,0.779853,1.599731,-0.330532,1.046929e-12,3.382121,2.034614,1.053746,1.229286e-35,1.667089,...,-0.738557,7.882425e-09,0.996735,1.744327,NaN,NaN,0.750157,1.434931,-0.312817,0.000357
20,Cpz,0.334683,1.364319,NaN,NaN,1.756940,2.215950,0.532780,6.073441e-11,1.078223,...,NaN,NaN,0.118854,0.796596,NaN,NaN,0.249826,1.107035,NaN,NaN
30,App,-0.120403,1.018377,-0.499723,1.002941e-37,1.143971,0.987538,0.659077,1.273815e-19,1.061755,...,NaN,NaN,0.023743,0.903855,-0.416079,0.000004,0.303569,0.947741,NaN,NaN

In [217]:
# Access data by coordinates
df.iloc[10,10]

2.17216622965145

In [169]:
# Access the data row by row
for idx, gene in df.iterrows():
   print(idx,gene[early_groups])
    
print('hello')

hello

In [102]:
# Find data based on textual information
#df.loc[df['24.0_Avg_diff'] == 'Text I\'m interested in']
df2 = df[early_groups].fillna('missing')
df3 = df2.loc[df2['24.0_Avg_diff'] != 'missing']
df3['24.0_Avg_diff']

0       -0.731901
7       -0.530948
12       -0.27087
15      -0.417623
17      -0.634002
           ...
27641    0.293224
27651    0.262168
27653    0.636619
27852     0.36567
27890   -0.291143
Name: 24.0_Avg_diff, Length: 636, dtype: object

In [75]:
# Filtering
#df.loc[(df['Field1'] == 'something') & (df['Field2'] == 'somethine_else')]
new_df = df.loc[df['24.0_Avg_diff'] > 0]
# But the index values for the filtered data are the same as the original.
# Let's make a new dataframe that has reset indices
new_df.reset_index(,inplace=True) # inplace so we don't have to make a new variable
new_df

,Unnamed: 0,10.0_Mean,10.0_SD,10.0_Avg_diff,10.0_Pval,10.1.0_Mean,10.1.0_SD,10.1.0_Avg_diff,10.1.0_Pval,10.1.1_Mean,...,22.3_Pval,24.0_Mean,24.0_SD,24.0_Avg_diff,24.0_Pval,24.1_Mean,24.1_SD,24.1_Avg_diff,24.1_Pval,new column
0,Ccnd1,0.369192,1.321405,NaN,NaN,0.693116,1.363071,0.265211,1.706978e-02,1.252291,...,3.156399e-10,0.943219,1.354246,0.509836,4.503701e-06,1.548763,1.060747,0.807446,2.364306e-20,2.338468
1,Ptp4a2,0.025979,1.087775,NaN,NaN,0.533614,1.266070,0.411101,2.933181e-08,0.338547,...,NaN,0.428795,1.157104,0.255234,1.284547e-02,0.084073,1.038042,NaN,NaN,2.210785
2,Akr1b3,-0.044302,1.032380,NaN,NaN,0.284036,1.186561,NaN,NaN,-0.231145,...,NaN,0.356064,1.153120,0.261191,8.231169e-03,0.075269,1.023164,NaN,NaN,1.470597
3,Mrpl51,0.002811,1.107426,NaN,NaN,-0.283433,0.938012,NaN,NaN,-0.073600,...,NaN,0.424925,1.086524,0.346588,6.715937e-05,0.210272,1.111419,NaN,NaN,0.654578
4,Cbx3,0.048444,1.077367,NaN,NaN,-0.038278,1.067017,NaN,NaN,-0.038545,...,NaN,0.436001,1.235148,0.489286,3.162485e-06,0.410696,1.195591,0.442889,8.690963e-05,1.028739
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
406,Kif20b,-0.223696,0.530864,NaN,NaN,-0.153480,0.670156,NaN,NaN,-0.241614,...,NaN,1.653342,2.065411,0.945851,5.917169e-42,0.334125,1.367477,NaN,NaN,0.516675
407,Rpp30,-0.073529,0.976803,NaN,NaN,0.083442,1.115204,NaN,NaN,0.035083,...,NaN,0.415085,1.453267,0.293224,6.298890e-04,0.286694,1.313942,NaN,NaN,1.198646
408,2019-03-05 00:00:00,0.150185,1.178914,NaN,NaN,0.078095,1.097935,NaN,NaN,-0.013348,...,NaN,0.561594,1.147275,0.262168,2.796793e-03,0.269163,1.128335,NaN,NaN,1.176031
409,Kif11,-0.223416,0.220172,NaN,NaN,-0.190114,0.441262,NaN,NaN,-0.227029,...,NaN,1.188096,2.322292,0.636619,2.724313e-29,0.237476,1.323907,NaN,NaN,0.251147
410,Acsl5,0.337262,1.583403,NaN,NaN,-0.130103,0.667195,NaN,NaN,-0.157150,...,NaN,1.201685,2.169808,0.365670,4.787458e-06,0.469143,1.590630,NaN,NaN,0.537092

In [274]:
early_diffs[1]

'24.0_Avg_diff'

In [275]:
# Filter null values for a specific group
df_earlydiffs.loc[~df_earlydiffs[early_diffs[1]].isnull()].reset_index()

,index,Gene,24.0_Avg_diff,24.1_Avg_diff,10.0_Avg_diff,10.1.0_Avg_diff,10.1.1_Avg_diff,10.4_Avg_diff,10.2.1_Avg_diff,10.3.0_Avg_diff
0,0,Apoe,-0.731901,-0.419621,-0.891624,0.573273,NaN,-0.458542,-0.764717,-0.746512
1,7,Krt18,-0.530948,-0.485152,-0.613109,NaN,0.499787,0.411182,NaN,-0.755791
2,12,Tpbg,-0.270870,-0.337939,-0.264440,0.474989,NaN,NaN,NaN,-0.440207
3,15,Mgst1,-0.417623,-0.491978,-0.285080,0.628995,0.500010,-0.392868,-0.263534,NaN
4,17,Krt8,-0.634002,-0.855731,-0.853618,NaN,0.512157,NaN,-0.674847,-0.525818
...,...,...,...,...,...,...,...,...,...,...
631,27641,Rpp30,0.293224,NaN,NaN,NaN,NaN,NaN,NaN,NaN
632,27651,2019-03-05 00:00:00,0.262168,NaN,NaN,NaN,NaN,NaN,NaN,NaN
633,27653,Kif11,0.636619,NaN,NaN,NaN,NaN,NaN,NaN,NaN
634,27852,Acsl5,0.365670,NaN,NaN,NaN,NaN,NaN,NaN,NaN
635,27890,Rps12-ps3,-0.291143,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [276]:
# Filter and sort high expressing genes for a specific group
df_earlydiffs.loc[df_earlydiffs[early_diffs[4]] > 1.3].\
sort_values(by=[early_diffs[4]],ascending=False)\
.reset_index()

,index,Gene,24.0_Avg_diff,24.1_Avg_diff,10.0_Avg_diff,10.1.0_Avg_diff,10.1.1_Avg_diff,10.4_Avg_diff,10.2.1_Avg_diff,10.3.0_Avg_diff
0,1,Bmp4,NaN,NaN,NaN,2.097418,0.597864,NaN,NaN,NaN
1,4,Hs3st1,NaN,NaN,-0.826899,1.401558,0.989634,NaN,NaN,0.35871
2,5,Gata2,NaN,NaN,NaN,1.373971,0.538055,NaN,NaN,NaN
3,3,Lmo3,NaN,NaN,NaN,1.310493,NaN,NaN,NaN,NaN

In [277]:
# Find data for a specific gene
df_earlydiffs.loc[df_earlydiffs['Gene'] == 'Dll1']

,Gene,24.0_Avg_diff,24.1_Avg_diff,10.0_Avg_diff,10.1.0_Avg_diff,10.1.1_Avg_diff,10.4_Avg_diff,10.2.1_Avg_diff,10.3.0_Avg_diff
24734,Dll1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [297]:
# Find data for a gene family (e.g. all Bmps or all Wnts)
df_alldiffs.loc[df_alldiffs['Gene'].str.contains('Fgf',na=False)]

,Gene,10.1.1_Avg_diff,10.1.2_Avg_diff,10.1.3_Avg_diff,10.2.0_Avg_diff,10.2.1_Avg_diff,10.3.0_Avg_diff,10.3.1_Avg_diff,10.3.2_Avg_diff,10.4_Avg_diff,10.5_Avg_diff,22.0_Avg_diff,22.1_Avg_diff,22.2.0_Avg_diff,22.2.1_Avg_diff,22.3_Avg_diff,24.0_Avg_diff,24.1_Avg_diff
268,Fgfr2,NaN,0.251343,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3906,Fgf7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5147,Fgf13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5443,Fgf16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6002,Fgf2os,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6003,Fgf2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9179,Fgfr3,NaN,NaN,NaN,NaN,NaN,NaN,1.210905,1.361608,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9289,Fgfbp1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9678,Fgf5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9814,Fgfrl1,NaN,NaN,NaN,NaN,NaN,NaN,0.350199,NaN,NaN,NaN,NaN,NaN,NaN,0.343652,NaN,NaN,NaN
11811,Fgf6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11812,Fgf23,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12064,Fgfr1op2,NaN,NaN,-0.393303,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13157,Fgf21,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14522,Fgf3,NaN,NaN,NaN,NaN,NaN,NaN,0.479940,0.564508,NaN,1.235103,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14523,Fgf4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14525,Fgf15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15083,Fgf22,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15942,Fgfr1,NaN,NaN,NaN,0.279341,NaN,NaN,0.422623,NaN,NaN,NaN,0.293705,NaN,NaN,NaN,0.277941,NaN,NaN
16025,Fgf20,NaN,NaN,NaN,NaN,NaN,0.691805,NaN,NaN,NaN,0.437560,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17597,Fgf9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17753,Fgf17,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17907,Fgf14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19573,Fgf18,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20098,Fgf11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21787,Fgfr4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22255,Fgf10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.535836,NaN,NaN,0.366954,0.473394,NaN,NaN,NaN
24183,Fgf12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24676,Fgfr1op,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26849,Fgf1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27647,Fgfbp3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27779,Fgf8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [279]:
df_earlydiffs[early_diffs[0]].str.contains('Dll').sort_values(ascending=False)

3800      True
24734     True
12724     True
27997    False
9324     False
         ...
23933      NaN
24087      NaN
25141      NaN
26937      NaN
27651      NaN
Name: Gene, Length: 27998, dtype: object